<Type Name="UnhandledExceptionAction" FullName="System.Activities.UnhandledExceptionAction">
  <TypeSignature Language="C#" Value="public enum UnhandledExceptionAction" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi sealed UnhandledExceptionAction extends System.Enum" />
  <AssemblyInfo>
    <AssemblyName>System.Activities</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Enum</BaseTypeName>
  </Base>
  <Docs>
    <summary>Specifies the action that occurs when an exception escapes the root of a workflow.</summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 The <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> function is invoked if an exception escapes the root of the workflow. The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> provides access to the exception as well as a pointer to the <xref:System.Activities.Activity> that generated the exception. F:System.Activities.UnhandledExceptionAction.Terminate?qualifyHint=False&autoUpgrade=True is the default action if no P:System.Activities.WorkflowApplication.OnUnhandledException?qualifyHint=False&autoUpgrade=True handler is specified.  
  
   
  
## Examples  
 The following example invokes a workflow that throws an exception. The exception is unhandled by the workflow and the P:System.Activities.WorkflowApplication.OnUnhandledException?qualifyHint=False&autoUpgrade=True handler is invoked. The T:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs?qualifyHint=False&autoUpgrade=True are inspected to provide information about the exception, and the workflow is terminated.  
  
 [!CODE [CFX_WorkflowApplicationExample#6](../CodeSnippet/VS_Snippets_CFX/cfx_workflowapplicationexample#6)]  
  
 ]]></format>
    </remarks>
  </Docs>
  <Members>
    <Member MemberName="Abort">
      <MemberSignature Language="C#" Value="Abort" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Activities.UnhandledExceptionAction Abort = int32(0)" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Activities.UnhandledExceptionAction</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>Specifies that the T:System.Activities.WorkflowApplication?qualifyHint=False&amp;autoUpgrade=True should abort the workflow.</summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 This results in P:System.Activities.WorkflowApplication.Aborted?qualifyHint=False&autoUpgrade=True being called when the abort process is complete. The unhandled exception is used as the abort reason.  
  
   
  
## Examples  
 The following example invokes a workflow that throws an exception. The exception is unhandled by the workflow and the P:System.Activities.WorkflowApplication.OnUnhandledException?qualifyHint=False&autoUpgrade=True handler is invoked. The T:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs?qualifyHint=False&autoUpgrade=True are inspected to provide information about the exception, and the workflow is aborted.  
  
 [!CODE [CFX_WorkflowApplicationExample#7](../CodeSnippet/VS_Snippets_CFX/cfx_workflowapplicationexample#7)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="Cancel">
      <MemberSignature Language="C#" Value="Cancel" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Activities.UnhandledExceptionAction Cancel = int32(1)" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Activities.UnhandledExceptionAction</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>Specifies that the T:System.Activities.WorkflowApplication?qualifyHint=False&amp;autoUpgrade=True should schedule the cancellation of the root activity and resume execution.</summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 This results in P:System.Activities.WorkflowApplication.Completed?qualifyHint=False&autoUpgrade=True being called when the cancellation process is complete.  
  
   
  
## Examples  
 The following example invokes a workflow that throws an exception. The exception is unhandled by the workflow and the P:System.Activities.WorkflowApplication.OnUnhandledException?qualifyHint=False&autoUpgrade=True handler is invoked. The T:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs?qualifyHint=False&autoUpgrade=True are inspected to provide information about the exception, and the workflow is cancelled.  
  
 [!CODE [CFX_WorkflowApplicationExample#8](../CodeSnippet/VS_Snippets_CFX/cfx_workflowapplicationexample#8)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="Terminate">
      <MemberSignature Language="C#" Value="Terminate" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Activities.UnhandledExceptionAction Terminate = int32(2)" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Activities.UnhandledExceptionAction</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>Specifies that the T:System.Activities.WorkflowApplication?qualifyHint=False&amp;autoUpgrade=True should schedule termination of the root activity and resume execution.</summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 This results in P:System.Activities.WorkflowApplication.Completed?qualifyHint=False&autoUpgrade=True being called when the termination process is complete. The unhandled exception is used as the termination reason. F:System.Activities.UnhandledExceptionAction.Terminate?qualifyHint=False&autoUpgrade=True is the default action if no P:System.Activities.WorkflowApplication.OnUnhandledException?qualifyHint=False&autoUpgrade=True handler is specified.  
  
   
  
## Examples  
 The following example invokes a workflow that throws an exception. The exception is unhandled by the workflow and the P:System.Activities.WorkflowApplication.OnUnhandledException?qualifyHint=False&autoUpgrade=True handler is invoked. The T:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs?qualifyHint=False&autoUpgrade=True are inspected to provide information about the exception, and the workflow is terminated.  
  
 [!CODE [CFX_WorkflowApplicationExample#6](../CodeSnippet/VS_Snippets_CFX/cfx_workflowapplicationexample#6)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>