<Type Name="AbandonedMutexException" FullName="System.Threading.AbandonedMutexException">
  <TypeSignature Language="C#" Value="public class AbandonedMutexException : SystemException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable beforefieldinit AbandonedMutexException extends System.SystemException" />
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.SystemException</BaseTypeName>
  </Base>
  <Interfaces />
  <Attributes>
    <Attribute>
      <AttributeName>System.Runtime.InteropServices.ComVisible(false)</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary>The exception that is thrown when one thread acquires a &lt;see cref="T:System.Threading.Mutex"&gt; object that another thread has abandoned by exiting without releasing it.</summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 When a thread abandons a mutex, the exception is thrown in the next thread that acquires the mutex. The thread might acquire the mutex because it was already waiting on the mutex or because it enters the mutex at a later time.  
  
 An abandoned mutex indicates a serious programming error. When a thread exits without releasing the mutex, the data structures protected by the mutex might not be in a consistent state. Prior to version 2.0 of the .NET Framework, such problems were hard to discover because no exception was thrown if a wait completed as the result of an abandoned mutex. For more information, see the <xref:System.Threading.Mutex> class.  
  
 The next thread to request ownership of the mutex can handle this exception and proceed, provided that the integrity of the data structures can be verified.  
  
   
  
## Examples  
 The following code example executes a thread that abandons five mutexes, demonstrating their effects on the <xref:System.Threading.WaitHandle.WaitOne%2A>, <xref:System.Threading.WaitHandle.WaitAny%2A>, and <xref:System.Threading.WaitHandle.WaitAll%2A> methods. The value of the <xref:System.Threading.AbandonedMutexException.MutexIndex%2A> property is displayed for the <xref:System.Threading.WaitHandle.WaitAny%2A> call.  
  
> [!NOTE]
>  The call to the <xref:System.Threading.WaitHandle.WaitAny%2A> method is interrupted by one of the abandoned mutexes. The other abandoned mutex could still cause an AbandonedMutexException to be thrown by subsequent wait methods.  
  
 [!CODE [System.Threading.AbandonedMutexException#1](../CodeSnippet/VS_Snippets_CLR_System/system.Threading.AbandonedMutexException#1)]  
  
 ]]></format>
    </remarks>
  </Docs>
  <Members>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AbandonedMutexException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary>Initializes a new instance of the &lt;see cref="T:System.Threading.AbandonedMutexException"&gt; class with default values.</summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as "The wait completed due to an abandoned mutex." This message takes into account the current system culture.  
  
 The following table shows the initial property values for an instance of <xref:System.Threading.AbandonedMutexException>.  
  
|Property|Value|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|`null`.|  
|<xref:System.Exception.Message%2A>|The system-supplied error message string.|  
|<xref:System.Threading.AbandonedMutexException.Mutex%2A>|`null`.|  
|<xref:System.Threading.AbandonedMutexException.MutexIndex%2A>|–1 (minus one).|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AbandonedMutexException (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message">An error message that explains the reason for the exception.</param>
        <summary>Initializes a new instance of the &lt;see cref="T:System.Threading.AbandonedMutexException"&gt; class with a specified error message.</summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 The content of  is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  
  
 The following table shows the initial property values for an instance of <xref:System.Threading.AbandonedMutexException> initialized with this constructor.  
  
|Property|Value|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|`null`.|  
|<xref:System.Exception.Message%2A>|.|  
|<xref:System.Threading.AbandonedMutexException.Mutex%2A>|`null`.|  
|<xref:System.Threading.AbandonedMutexException.MutexIndex%2A>|–1 (minus one).|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AbandonedMutexException (int location, System.Threading.WaitHandle handle);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(int32 location, class System.Threading.WaitHandle handle) cil managed" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="location" Type="System.Int32" />
        <Parameter Name="handle" Type="System.Threading.WaitHandle" />
      </Parameters>
      <Docs>
        <param name="location">The index of the abandoned mutex in the array of wait handles if the exception is thrown for the &lt;xref:System.Threading.WaitHandle.WaitAny%2A?displayProperty=fullName&gt; method, or –1 if the exception is thrown for the &lt;xref:System.Threading.WaitHandle.WaitOne%2A&gt; or &lt;xref:System.Threading.WaitHandle.WaitAll%2A&gt; methods.</param>
        <param name="handle">A &lt;see cref="T:System.Threading.Mutex"&gt; object that represents the abandoned mutex.</param>
        <summary>Initializes a new instance of the &lt;see cref="T:System.Threading.AbandonedMutexException"&gt; class with a specified index for the abandoned mutex, if applicable, and a &lt;xref:System.Threading.Mutex&gt; object that represents the mutex.</summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as "The wait completed due to an abandoned mutex." This message takes into account the current system culture.  
  
 The following table shows the initial property values for an instance of <xref:System.Threading.AbandonedMutexException> initialized with this constructor.  
  
|Property|Value|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|`null`.|  
|<xref:System.Exception.Message%2A>|A system-supplied error message string.|  
|<xref:System.Threading.AbandonedMutexException.Mutex%2A>|.|  
|<xref:System.Threading.AbandonedMutexException.MutexIndex%2A>|.|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="protected AbandonedMutexException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method familyhidebysig specialname rtspecialname instance void .ctor(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info">The &lt;see cref="T:System.Runtime.Serialization.SerializationInfo"&gt; object that holds the serialized object data about the exception being thrown.</param>
        <param name="context">The &lt;see cref="T:System.Runtime.Serialization.StreamingContext"&gt; object that contains contextual information about the source or destination.</param>
        <summary>Initializes a new instance of the &lt;see cref="T:System.Threading.AbandonedMutexException"&gt; class with serialized data.</summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](../Topic/XML%20and%20SOAP%20Serialization.md).  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AbandonedMutexException (string message, Exception inner);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception inner) cil managed" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="inner" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message">An error message that explains the reason for the exception.</param>
        <param name="inner">The exception that is the cause of the current exception. If the  parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.</param>
        <summary>Initializes a new instance of the &lt;see cref="T:System.Threading.AbandonedMutexException"&gt; class with a specified error message and inner exception.</summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 The content of  is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  
  
 An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  
  
 The following table shows the initial property values for an instance of <xref:System.Threading.AbandonedMutexException> initialized with this constructor.  
  
|Property|Value|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|.|  
|<xref:System.Exception.Message%2A>|.|  
|<xref:System.Threading.AbandonedMutexException.Mutex%2A>|`null`.|  
|<xref:System.Threading.AbandonedMutexException.MutexIndex%2A>|–1 (minus one).|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AbandonedMutexException (string message, int location, System.Threading.WaitHandle handle);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, int32 location, class System.Threading.WaitHandle handle) cil managed" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="location" Type="System.Int32" />
        <Parameter Name="handle" Type="System.Threading.WaitHandle" />
      </Parameters>
      <Docs>
        <param name="message">An error message that explains the reason for the exception.</param>
        <param name="location">The index of the abandoned mutex in the array of wait handles if the exception is thrown for the &lt;xref:System.Threading.WaitHandle.WaitAny%2A?displayProperty=fullName&gt; method, or –1 if the exception is thrown for the &lt;xref:System.Threading.WaitHandle.WaitOne%2A?displayProperty=fullName&gt; or &lt;xref:System.Threading.WaitHandle.WaitAll%2A&gt; methods.</param>
        <param name="handle">A &lt;see cref="T:System.Threading.Mutex"&gt; object that represents the abandoned mutex.</param>
        <summary>Initializes a new instance of the &lt;see cref="T:System.Threading.AbandonedMutexException"&gt; class with a specified error message, the index of the abandoned mutex, if applicable, and the abandoned mutex.</summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 The content of  is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  
  
 The following table shows the initial property values for an instance of <xref:System.Threading.AbandonedMutexException> initialized with this constructor.  
  
|Property|Value|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|`null`.|  
|<xref:System.Exception.Message%2A>|.|  
|<xref:System.Threading.AbandonedMutexException.Mutex%2A>|.|  
|<xref:System.Threading.AbandonedMutexException.MutexIndex%2A>|.|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public AbandonedMutexException (string message, Exception inner, int location, System.Threading.WaitHandle handle);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception inner, int32 location, class System.Threading.WaitHandle handle) cil managed" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="inner" Type="System.Exception" />
        <Parameter Name="location" Type="System.Int32" />
        <Parameter Name="handle" Type="System.Threading.WaitHandle" />
      </Parameters>
      <Docs>
        <param name="message">An error message that explains the reason for the exception.</param>
        <param name="inner">The exception that is the cause of the current exception. If the  parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.</param>
        <param name="location">The index of the abandoned mutex in the array of wait handles if the exception is thrown for the &lt;xref:System.Threading.WaitHandle.WaitAny%2A?displayProperty=fullName&gt; method, or –1 if the exception is thrown for the &lt;xref:System.Threading.WaitHandle.WaitOne%2A?displayProperty=fullName&gt; or &lt;xref:System.Threading.WaitHandle.WaitAll%2A&gt; methods.</param>
        <param name="handle">A &lt;see cref="T:System.Threading.Mutex"&gt; object that represents the abandoned mutex.</param>
        <summary>Initializes a new instance of the &lt;see cref="T:System.Threading.AbandonedMutexException"&gt; class with a specified error message, the inner exception, the index for the abandoned mutex, if applicable, and a &lt;xref:System.Threading.Mutex&gt; object that represents the mutex.</summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 The content of  is a text string intended to inform the user about the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  
  
 An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  
  
 The following table shows the initial property values for an instance of <xref:System.Threading.AbandonedMutexException> initialized with this constructor.  
  
|Property|Value|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|.|  
|<xref:System.Exception.Message%2A>|.|  
|<xref:System.Threading.AbandonedMutexException.Mutex%2A>|.|  
|<xref:System.Threading.AbandonedMutexException.MutexIndex%2A>|.|  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="Mutex">
      <MemberSignature Language="C#" Value="public System.Threading.Mutex Mutex { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Threading.Mutex Mutex" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Threading.Mutex</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>Gets the abandoned mutex that caused the exception, if known.</summary>
        <value>A &lt;see cref="T:System.Threading.Mutex"&gt; object that represents the abandoned mutex, or `null` if the abandoned mutex could not be identified.</value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 If the exception is thrown on a call to the <xref:System.Threading.WaitHandle.WaitAny%2A?displayProperty=fullName> method, the <xref:System.Threading.Mutex> returned is the abandoned mutex with the lowest index in the array of <xref:System.Threading.WaitHandle> objects that was passed to <xref:System.Threading.WaitHandle.WaitAny%2A>, or `null` if the abandoned mutex could not be identified. If the exception is thrown on a call to <xref:System.Threading.WaitHandle.WaitOne%2A> or <xref:System.Threading.WaitHandle.WaitAll%2A>, this property always returns `null`.  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="MutexIndex">
      <MemberSignature Language="C#" Value="public int MutexIndex { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance int32 MutexIndex" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Int32</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>Gets the index of the abandoned mutex that caused the exception, if known.</summary>
        <value>The index, in the array of wait handles passed to the &lt;xref:System.Threading.WaitHandle.WaitAny%2A?displayProperty=fullName&gt; method, of the &lt;xref:System.Threading.Mutex&gt; object that represents the abandoned mutex, or –1 if the index of the abandoned mutex could not be determined.</value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 If the exception is thrown on a call to the <xref:System.Threading.WaitHandle.WaitAny%2A?displayProperty=fullName> method, this property returns the index of the abandoned mutex with the lowest index in the array of <xref:System.Threading.WaitHandle> objects that was passed to <xref:System.Threading.WaitHandle.WaitAny%2A>, or –1 if the abandoned mutex could not be identified. If the exception is thrown on a call to <xref:System.Threading.WaitHandle.WaitOne%2A> or <xref:System.Threading.WaitHandle.WaitAll%2A>, this property always returns –1.  
  
   
  
## Examples  
 The following code example executes a thread that abandons five mutexes. The abandoned mutexes are used to demonstrate the effects on the <xref:System.Threading.WaitHandle.WaitOne%2A?displayProperty=fullName>, <xref:System.Threading.WaitHandle.WaitAny%2A>, and <xref:System.Threading.WaitHandle.WaitAll%2A> method calls. The value of the MutexIndex property is displayed for the <xref:System.Threading.WaitHandle.WaitAny%2A> call.  
  
> [!NOTE]
>  The call to <xref:System.Threading.WaitHandle.WaitAny%2A> is interrupted by one of the abandoned mutexes. The other abandoned mutex could still cause an <xref:System.Threading.AbandonedMutexException> to be thrown by subsequent wait methods.  
  
 [!CODE [System.Threading.AbandonedMutexException#1](../CodeSnippet/VS_Snippets_CLR_System/system.Threading.AbandonedMutexException#1)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>